[archimedlight-benchmark-scenes]
git-tree-sha1 = "0fe06e0ad6ecab2e7db5f97aff7d0ee11bb34555"
lazy = true

    [[archimedlight-benchmark-scenes.download]]
    sha256 = "6e761152d6024ed1f4ccbc30979f64fc643c9acfbb16fd593c5a851cb76affa7"
    url = "https://zenodo.org/records/21291758/files/benchmark-scenes.tar.gz?download=1"

[archimedlight-release-fixtures]
git-tree-sha1 = "522c0eb1b18b6714a4ffc3241d0409b478e11905"
lazy = true

    [[archimedlight-release-fixtures.download]]
    sha256 = "9034e2c2187b09b77d04c7cd2a9e544c83baed5c738b56072d383538fc2a2efc"
    url = "https://github.com/VEZY/ArchimedLight.jl/releases/download/v0.1.3/archimedlight-release-fixtures-v0.1.3.tar.gz"
